kind: Service
apiVersion: v1
metadata:
  name: store-products
spec:
  selector:
    app: store-products
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30001
